import mongoose from 'mongoose';
import generateOrderNumber from '../../utils/generateOrderNumber.js';

// ✅ Order Item - Stores product snapshot (price at time of order)
const orderItemSchema = new mongoose.Schema({
  product: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Product',
    required: true,
  },
  productName: {
    type: String,
    required: true,
  },
  sku: String,
  image: String,
  unitPrice: {
    type: Number,
    required: true,
    min: 0,
  },
  quantity: {
    type: Number,
    required: true,
    min: 1,
  },
  subtotal: {
    type: Number,
    required: true,
    min: 0,
  },
}, { _id: false });

const orderSchema = new mongoose.Schema({  // 🔑 Order Identifiers
  orderNumber: {
    type: String,
    unique: true,
    index: true,
    // Auto-generated by pre-save hook: ORD-{timestamp}-{count}
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },

  // 📦 Order Items (product snapshots)
  items: [orderItemSchema],

  // 💰 Pricing Breakdown (calculated by backend, NEVER from frontend)
  subtotal: {
    type: Number,
    required: true,
    min: 0,
  },
  tax: {
    type: Number,
    default: 0,
    min: 0,
  },
  shippingCost: {
    type: Number,
    default: 0,
    min: 0,
  },
  totalAmount: {
    type: Number,
    required: true,
    min: 0,
    index: true,
  },

  // ✅ Order Status (CRITICAL business rules)
  status: {
    type: String,
    enum: [
      'PENDING_PAYMENT',    // Order created, awaiting payment
      'PAID',               // Payment successful
      'PAYMENT_FAILED',     // Payment failed
      'PROCESSING',         // Payment successful, preparing to ship
      'SHIPPED',            // Order shipped
      'DELIVERED',          // Order delivered
      'CANCELLED',          // Order cancelled
      'REFUNDED',           // Refund processed
    ],
    default: 'PENDING_PAYMENT',
    index: true,
  },

  // 💳 Payment Information
  payment: {
    transactionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Payment' },
    method: { type: String, enum: ['mtn_money', 'orange_money', 'credit_card', 'bank_transfer'] },
    status: { 
      type: String,
      enum: ['PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED'],
      default: 'PENDING_PAYMENT',
    },
  },
  // 🚚 Shipping Information
  shippingAddress: {
    fullName: String,
    phone: String,
    email: String,
    address: String,
    city: String,
    region: String,
    postalCode: { type: String, default: '0000' },
    country: { type: String, default: 'Cameroon' },
  },

  // 📝 Customer Information
  customerName: {
    type: String,
    required: true,
  },
  customerPhone: {
    type: String,
    required: true,
  },
  customerEmail: String,

  // ⏰ Timeline
  paidAt: Date,
  shippedAt: Date,
  deliveredAt: Date,
  cancelledAt: Date,
  refundedAt: Date,

  // 📋 Notes
  notes: String,

}, { timestamps: true });

// 🔐 Auto-generate order number before saving (if new document)
orderSchema.pre('save', async function (next) {
  try {
    if (this.isNew && !this.orderNumber) {
      const count = await mongoose.model('Order').countDocuments();
      this.orderNumber = `ORD-${Date.now()}-${count + 1}`;
    }
    next();
  } catch (error) {
    next(error);
  }
});

const Order = mongoose.model('Order', orderSchema);
export default Order;
